<!--
This HTML is auto-generated.  DO NOT EDIT THIS FILE!  If you are writing a new
PEP, see http://www.python.org/dev/peps/pep-0001 for instructions and links
to templates.  DO NOT USE THIS HTML FILE AS YOUR TEMPLATE!
-->
<table class="rfc2822 docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field"><th class="field-name">PEP:</th><td class="field-body">473</td>
</tr>
<tr class="field"><th class="field-name">Title:</th><td class="field-body">Adding structured data to built-in exceptions</td>
</tr>
<tr class="field"><th class="field-name">Version:</th><td class="field-body">$Revision$</td>
</tr>
<tr class="field"><th class="field-name">Last-Modified:</th><td class="field-body"><a class="reference external" href="https://hg.python.org/peps/file/tip/pep-0473.txt">$Date$</a></td>
</tr>
<tr class="field"><th class="field-name">Author:</th><td class="field-body">Sebastian Kreft &lt;skreft&#32;&#97;t&#32;deezer.com&gt;</td>
</tr>
<tr class="field"><th class="field-name">Status:</th><td class="field-body">Draft</td>
</tr>
<tr class="field"><th class="field-name">Type:</th><td class="field-body">Standards Track</td>
</tr>
<tr class="field"><th class="field-name">Content-Type:</th><td class="field-body"><a class="reference external" href="/dev/peps/pep-0012">text/x-rst</a></td>
</tr>
<tr class="field"><th class="field-name">Created:</th><td class="field-body">29-Mar-2014</td>
</tr>
<tr class="field"><th class="field-name">Post-History:</th><td class="field-body"></td>
</tr>
</tbody>
</table>
<hr />
<div class="contents topic" id="contents">
<p class="topic-title first">Contents</p>
<ul class="simple">
<li><a class="reference internal" href="#abstract" id="id40">Abstract</a></li>
<li><a class="reference internal" href="#rationale" id="id41">Rationale</a></li>
<li><a class="reference internal" href="#examples" id="id42">Examples</a><ul>
<li><a class="reference internal" href="#indexerror" id="id43">IndexError</a></li>
<li><a class="reference internal" href="#keyerror" id="id44">KeyError</a></li>
<li><a class="reference internal" href="#attributeerror" id="id45">AttributeError</a></li>
<li><a class="reference internal" href="#nameerror" id="id46">NameError</a></li>
<li><a class="reference internal" href="#other-cases" id="id47">Other Cases</a></li>
</ul>
</li>
<li><a class="reference internal" href="#proposal" id="id48">Proposal</a></li>
<li><a class="reference internal" href="#potential-uses" id="id49">Potential Uses</a></li>
<li><a class="reference internal" href="#performance" id="id50">Performance</a></li>
<li><a class="reference internal" href="#references" id="id51">References</a></li>
<li><a class="reference internal" href="#copyright" id="id52">Copyright</a></li>
</ul>
</div>
<div class="section" id="abstract">
<h1><a class="toc-backref" href="#id40">Abstract</a></h1>
<p>Exceptions like <tt class="docutils literal">AttributeError</tt>, <tt class="docutils literal">IndexError</tt>, <tt class="docutils literal">KeyError</tt>,
<tt class="docutils literal">LookupError</tt>, <tt class="docutils literal">NameError</tt>, <tt class="docutils literal">TypeError</tt>, and <tt class="docutils literal">ValueError</tt> do not
provide all information required by programmers to debug and better understand
what caused them.
Furthermore, in some cases the messages even have slightly different formats,
which makes it really difficult for tools to automatically provide additional
information to diagnose the problem.
To tackle the former and to lay ground for the latter, it is proposed to expand
these exceptions so to hold both the offending and affected entities.</p>
</div>
<div class="section" id="rationale">
<h1><a class="toc-backref" href="#id41">Rationale</a></h1>
<p>The main issue this PEP aims to solve is the fact that currently error messages
are not that expressive and lack some key information to resolve the exceptions.
Additionally, the information present on the error message is not always in the
same format, which makes it very difficult for third-party libraries to
provide automated diagnosis of the error.</p>
<p>These automated tools could, for example, detect typos or display or log extra
debug information. These could be particularly useful when running tests or in a
long running application.</p>
<p>Although it is in theory possible to have such libraries, they need to resort to
hacks in order to achieve the goal. One such example is
python-improved-exceptions <a class="footnote-reference" href="#id27" id="id1">[1]</a>, which modifies the byte-code to keep references
to the possibly interesting objects and also parses the error messages to
extract information like types or names. Unfortunately, such approach is
extremely fragile and not portable.</p>
<p>A similar proposal <a class="footnote-reference" href="#id28" id="id2">[2]</a> has been implemented for <tt class="docutils literal">ImportError</tt> and in the same
fashion this idea has received support <a class="footnote-reference" href="#id29" id="id3">[3]</a>. Additionally, almost 10 years ago
Guido asked in <a class="footnote-reference" href="#id37" id="id4">[11]</a> to have a clean API to access the affected objects in
Exceptions like <tt class="docutils literal">KeyError</tt>, <tt class="docutils literal">AttributeError</tt>, <tt class="docutils literal">NameError</tt>, and
<tt class="docutils literal">IndexError</tt>. Similar issues and proposals ideas have been written in the
last year. Some other issues have been created, but despite receiving support
they finally get abandoned. References to the created issues are listed below:</p>
<ul class="simple">
<li><tt class="docutils literal">AttributeError</tt>: <a class="footnote-reference" href="#id37" id="id5">[11]</a>, <a class="footnote-reference" href="#id36" id="id6">[10]</a>, <a class="footnote-reference" href="#id31" id="id7">[5]</a>, <a class="footnote-reference" href="#id30" id="id8">[4]</a>, <a class="footnote-reference" href="#id29" id="id9">[3]</a></li>
<li><tt class="docutils literal">IndexError</tt>: <a class="footnote-reference" href="#id37" id="id10">[11]</a>, <a class="footnote-reference" href="#id32" id="id11">[6]</a>, <a class="footnote-reference" href="#id29" id="id12">[3]</a></li>
<li><tt class="docutils literal">KeyError</tt>: <a class="footnote-reference" href="#id37" id="id13">[11]</a>, <a class="footnote-reference" href="#id33" id="id14">[7]</a>, <a class="footnote-reference" href="#id29" id="id15">[3]</a></li>
<li><tt class="docutils literal">LookupError</tt>: <a class="footnote-reference" href="#id37" id="id16">[11]</a></li>
<li><tt class="docutils literal">NameError</tt>: <a class="footnote-reference" href="#id37" id="id17">[11]</a>, <a class="footnote-reference" href="#id36" id="id18">[10]</a>, <a class="footnote-reference" href="#id29" id="id19">[3]</a></li>
<li><tt class="docutils literal">TypeError</tt>: <a class="footnote-reference" href="#id34" id="id20">[8]</a></li>
<li><tt class="docutils literal">ValueError</tt>: <a class="footnote-reference" href="#id35" id="id21">[9]</a></li>
</ul>
<p>To move forward with the development and to centralize the information and
discussion, this PEP aims to be a meta-issue summarizing all the above
discussions and ideas.</p>
</div>
<div class="section" id="examples">
<h1><a class="toc-backref" href="#id42">Examples</a></h1>
<div class="section" id="indexerror">
<h2><a class="toc-backref" href="#id43">IndexError</a></h2>
<p>The error message does not reference the list's length nor the index used.</p>
<pre class="literal-block">
a = [1, 2, 3, 4, 5]
a[5]
IndexError: list index out of range
</pre>
</div>
<div class="section" id="keyerror">
<h2><a class="toc-backref" href="#id44">KeyError</a></h2>
<p>By convention the key is the first element of the error's argument, but there's
no other information regarding the affected dictionary (keys types, size, etc.)</p>
<pre class="literal-block">
b = {'foo': 1}
b['fo']
KeyError: 'fo'
</pre>
</div>
<div class="section" id="attributeerror">
<h2><a class="toc-backref" href="#id45">AttributeError</a></h2>
<p>The object's type and the offending attribute are part of the error message.
However, there are some different formats and the information is not always
available. Furthermore, although the object type is useful in some cases, given
the dynamic nature of Python, it would be much more useful to have a reference
to the object itself. Additionally the reference to the type is not fully
qualified and in some cases the type is just too generic to provide useful
information, for example in case of accessing a module's attribute.</p>
<pre class="literal-block">
c = object()
c.foo
AttributeError: 'object' object has no attribute 'foo'

import string
string.foo
AttributeError: 'module' object has no attribute 'foo'

a = string.Formatter()
a.foo
AttributeError: 'Formatter' object has no attribute 'foo'
</pre>
</div>
<div class="section" id="nameerror">
<h2><a class="toc-backref" href="#id46">NameError</a></h2>
<p>The error message provides typically the name.</p>
<pre class="literal-block">
foo = 1
fo
NameError: global name 'fo' is not defined
</pre>
</div>
<div class="section" id="other-cases">
<h2><a class="toc-backref" href="#id47">Other Cases</a></h2>
<p>Issues are even harder to debug when the target object is the result of
another expression, for example:</p>
<pre class="literal-block">
a[b[c[0]]]
</pre>
<p>This issue is also related to the fact that opcodes only have line number
information and not the offset. This proposal would help in this case but not as
much as having offsets.</p>
</div>
</div>
<div class="section" id="proposal">
<h1><a class="toc-backref" href="#id48">Proposal</a></h1>
<p>Extend the exceptions <tt class="docutils literal">AttributeError</tt>, <tt class="docutils literal">IndexError</tt>, <tt class="docutils literal">KeyError</tt>,
<tt class="docutils literal">LookupError</tt>, <tt class="docutils literal">NameError</tt>, <tt class="docutils literal">TypeError</tt>, and <tt class="docutils literal">ValueError</tt> with the
following:</p>
<ul class="simple">
<li><tt class="docutils literal">AttributeError</tt>: target <sup>w</sup>, attribute</li>
<li><tt class="docutils literal">IndexError</tt>: target <sup>w</sup>, key <sup>w</sup>, index (just an alias to
key)</li>
<li><tt class="docutils literal">KeyError</tt>: target <sup>w</sup>, key <sup>w</sup></li>
<li><tt class="docutils literal">LookupError</tt>: target <sup>w</sup>, key <sup>w</sup></li>
<li><tt class="docutils literal">NameError</tt>: name, scope?</li>
<li><tt class="docutils literal">TypeError</tt>: unexpected_type</li>
<li><tt class="docutils literal">ValueError</tt>: unexpected_value <sup>w</sup></li>
</ul>
<p>Attributes with the superscript <sup>w</sup> may need to be weak references <a class="footnote-reference" href="#id38" id="id22">[12]</a> to
prevent any memory cycles. However, this may add an unnecessary extra
complexity as noted by R. David Murray <a class="footnote-reference" href="#id39" id="id23">[13]</a>. This is specially true given that
builtin types do not support being weak referenced.</p>
<p>TODO(skreft): expand this with examples of corner cases.</p>
<p>To remain backwards compatible these new attributes will be optional and keyword
only.</p>
<p>It is proposed to add this information, rather than just improve the error, as
the former would allow new debugging frameworks and tools and also in the future
to switch to a lazy generated message. Generated messages are discussed in <a class="footnote-reference" href="#id28" id="id24">[2]</a>,
although they are not implemented at the moment. They would not only save some
resources, but also uniform the messages.</p>
<p>The stdlib will be then gradually changed so to start using these new
attributes.</p>
</div>
<div class="section" id="potential-uses">
<h1><a class="toc-backref" href="#id49">Potential Uses</a></h1>
<p>An automated tool could for example search for similar keys within the object,
allowing to display the following::</p>
<pre class="literal-block">
a = {'foo': 1}
a['fo']
KeyError: 'fo'. Did you mean 'foo'?

foo = 1
fo
NameError: global name 'fo' is not defined. Did you mean 'foo'?
</pre>
<p>See <a class="footnote-reference" href="#id29" id="id25">[3]</a> for the output a TestRunner could display.</p>
</div>
<div class="section" id="performance">
<h1><a class="toc-backref" href="#id50">Performance</a></h1>
<p>Filling these new attributes would only require two extra parameters with data
already available so the impact should be marginal. However, it may need
special care for <tt class="docutils literal">KeyError</tt> as the following pattern is already widespread.</p>
<pre class="literal-block">
try:
  a[foo] = a[foo] + 1
except:
  a[foo] = 0
</pre>
<p>Note as well that storing these objects into the error itself would allow the
lazy generation of the error message, as discussed in <a class="footnote-reference" href="#id28" id="id26">[2]</a>.</p>
</div>
<div class="section" id="references">
<h1><a class="toc-backref" href="#id51">References</a></h1>
<table class="docutils footnote" frame="void" id="id27" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id1">[1]</a></td><td>Python Exceptions Improved
(<a class="reference external" href="https://www.github.com/sk-/python-exceptions-improved">https://www.github.com/sk-/python-exceptions-improved</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id28" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label">[2]</td><td><em>(<a class="fn-backref" href="#id2">1</a>, <a class="fn-backref" href="#id24">2</a>, <a class="fn-backref" href="#id26">3</a>)</em> ImportError needs attributes for module and file name
(<a class="reference external" href="http://bugs.python.org/issue1559549">http://bugs.python.org/issue1559549</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id29" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label">[3]</td><td><em>(<a class="fn-backref" href="#id3">1</a>, <a class="fn-backref" href="#id9">2</a>, <a class="fn-backref" href="#id12">3</a>, <a class="fn-backref" href="#id15">4</a>, <a class="fn-backref" href="#id19">5</a>, <a class="fn-backref" href="#id25">6</a>)</em> Enhance exceptions by attaching some more information to them
(<a class="reference external" href="https://mail.python.org/pipermail/python-ideas/2014-February/025601.html">https://mail.python.org/pipermail/python-ideas/2014-February/025601.html</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id30" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id8">[4]</a></td><td>Specifity in AttributeError
(<a class="reference external" href="https://mail.python.org/pipermail/python-ideas/2013-April/020308.html">https://mail.python.org/pipermail/python-ideas/2013-April/020308.html</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id31" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id7">[5]</a></td><td>Add an 'attr' attribute to AttributeError
(<a class="reference external" href="http://bugs.python.org/issue18156">http://bugs.python.org/issue18156</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id32" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id11">[6]</a></td><td>Add index attribute to IndexError
(<a class="reference external" href="http://bugs.python.org/issue18162">http://bugs.python.org/issue18162</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id33" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id14">[7]</a></td><td>Add a 'key' attribute to KeyError
(<a class="reference external" href="http://bugs.python.org/issue18163">http://bugs.python.org/issue18163</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id34" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id20">[8]</a></td><td>Add 'unexpected_type' to TypeError
(<a class="reference external" href="http://bugs.python.org/issue18165">http://bugs.python.org/issue18165</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id35" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id21">[9]</a></td><td>'value' attribute for ValueError
(<a class="reference external" href="http://bugs.python.org/issue18166">http://bugs.python.org/issue18166</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id36" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label">[10]</td><td><em>(<a class="fn-backref" href="#id6">1</a>, <a class="fn-backref" href="#id18">2</a>)</em> making builtin exceptions more informative
(<a class="reference external" href="http://bugs.python.org/issue1182143">http://bugs.python.org/issue1182143</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id37" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label">[11]</td><td><em>(<a class="fn-backref" href="#id4">1</a>, <a class="fn-backref" href="#id5">2</a>, <a class="fn-backref" href="#id10">3</a>, <a class="fn-backref" href="#id13">4</a>, <a class="fn-backref" href="#id16">5</a>, <a class="fn-backref" href="#id17">6</a>)</em> LookupError etc. need API to get the key
(<a class="reference external" href="http://bugs.python.org/issue614557">http://bugs.python.org/issue614557</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id38" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id22">[12]</a></td><td>weakref - Weak References
(<a class="reference external" href="https://docs.python.org/3/library/weakref.html">https://docs.python.org/3/library/weakref.html</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id39" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id23">[13]</a></td><td>Message by R.   David Murray: Weak refs on exceptions?
(<a class="reference external" href="http://bugs.python.org/issue18163#msg190791">http://bugs.python.org/issue18163#msg190791</a>)</td></tr>
</tbody>
</table>
</div>
<div class="section" id="copyright">
<h1><a class="toc-backref" href="#id52">Copyright</a></h1>
<p>This document has been placed in the public domain.</p>
<!-- Local Variables:
mode: indented-text
indent-tabs-mode: nil
sentence-end-double-space: t
fill-column: 70
coding: utf-8
End: -->
</div>

